### ISSUE TITLE
Add "filter" trigger type 

### ISSUE THREAD

**Issue by AlexKolonitsky** [AlexKolonitsky/lucidworks-view#12]
A category can accept a field name (e.g. 'category_id') and field value (e.g. '1000') which can support multiple values.  Support for a single value is the priority at this point - multiple can be added later.

**Comment by erikhatcher** [comment]
Just a single string input box will work just fine for now.  A user would enter literally "category:1000" as one string.  Separate field name and field value fields could be a future enhancement, but not currently supported.
