### ISSUE TITLE
Refresh grid and facets after toggling the ‘Enabled’ column button.

### ISSUE THREAD

**Issue by AlColeLW** [AlexKolonitsky/lucidworks-view#33]

**Comment by erikhatcher** [comment]
Alas, this is a bit of a tricky one.  The update goes through but the refresh happens generally faster than Solr has the update visible.  :/  Let's not worry about this one for DEMO purposes but maybe we put in a couple of second delay somewhere - like a spinner when a change occurs - could even poll the document to wait until a new `_version_` appears
