### ISSUE TITLE
Date triggers do not save to Solr

### ISSUE THREAD

**Issue by erikhatcher** [AlexKolonitsky/lucidworks-view#42]
![image](https://cloud.githubusercontent.com/assets/209189/16060526/23ae186e-3256-11e6-9a7e-d23e6f401a53.png)

Added that rule and it appeared in the UI, but refreshing didn't show it, so it had an error saving I bet.

Will look into logs to see what's being sent incorrectly, but I imagine the effective_range value sent isn't valid.  

A simpler thing would be to simply have a single text box to start with, as the syntax for this beast can be hairy to get just right, to be the best for what the business user needs to specify simply.

**Comment by erikhatcher** [comment]
Alex fixed date range saving, however it's not yet quite right.  I picked March 13, 2016 - March 15, 2016 and it set effective_range to `["2016-03-13","2016-03-15"]`, which is a trigger that means either the 13th or the 15th, but NOT the 14th.  :)    The right value would have been `["[2016-03-13 TO 2016-03-15]"]`

Workable for a demo - but we'll need to revisit how a user can enter effective ranges cleanly.

**Comment by AlexKolonitsky** [comment]
`[2000-11-01 TO 2014-12-01]` kinda syntax is all we need for now
