### ISSUE TITLE
QA: During rule editing - cannot add a DATE trigger

### ISSUE THREAD

**Issue by AlColeLW** [AlexKolonitsky/lucidworks-view#56]
Created a Filter List rule (create-a-shop) using a keyword.  I later edited the rule to add a date trigger and it would not show the date fields when selected in the menu list.  This appears to be slightly inconsistent because I am able to edit other rules and add a date trigger.  However, after the data trigger is selected, I cannot get the calendar control to display in the form - it is just a text field.

**Comment by erikhatcher** [comment]
I still think a good way to handle "editing" a rule after it is created is to simply re-use, and pop the same modal dialog used when creating a new rule.  Saves having to worry about "in-line editing" mode being different than create mode - all UI/validation/etc all the same.

**Comment by AlColeLW** [comment]
{"response":{"numFound":310,"start":0,"docs":[{"tags":["PROD"],"id":"lp-Unsubscribe","type":"response_value","display_type":"Redirect","search_terms":["Unsubscribe"],"keys":["redirect"],"values":["/custserv/custserv-0001.jsp"],"_version_":1538287480704335872,"created_date":"2016-06-27T11:01:01.59Z"},{"tags":["PROD"],"id":"lp-chat","type":"response_value","display_type":"Redirect","search_terms":["chat"],"keys":["redirect"],"values":["/custserv/custserv-0002.jsp"],"_version_":1538287480705384448,"created_date":"2016-06-27T11:01:01.59Z"},{"tags":["PROD"],"id":"lp-CustomerService","type":"response_value","display_type":"Redirect","search_terms":["Customer Service"],"keys":["redirect"],"values":["/custserv/custserv-0003.jsp"],"_version_":1538287480706433024,"created_date":"2016-06-27T11:01:01.59Z"},{"tags":["PROD"],"id":"lp-faq","type":"response_value","display_type":"Redirect","search_terms":["faq"],"keys":["redirect"],"values":["/custserv/custserv-0004.jsp"],"_version_":1538287480706433025,"created_date":"2016-06-27T11:01:01.59Z"},{"tags":["PROD"],"id":"lp-chitchat","type":"response_value","display_type":"Redirect","search_terms":["chitchat"],"keys":["redirect"],"values":["/custserv/custserv-0005.jsp"],"_version_":1538287480706433026,"created_date":"2016-06-27T11:01:01.59Z"},{"tags":["PROD"],"id":"lp-faqs","type":"response_value","display_type":"Redirect","search_terms":["faqs"],"keys":["redirect"],"values":["/custserv/custserv-0006.jsp"],"_version_":1538287480706433027,"created_date":"2016-06-27T11:01:01.59Z"},{"tags":["PROD"],"id":"lp-custserv","type":"response_value","display_type":"Redirect","search_terms":["custserv"],"keys":["redirect"],"values":["/custserv/custserv-0007.jsp"],"_version_":1538287480707481600,"created_date":"2016-06-27T11:01:01.59Z"},{"tags":["PROD"],"id":"lp-service","type":"response_value","display_type":"Redirect","search_terms":["service"],"keys":["redirect"],"values":["/custserv/custserv-0008.jsp"],"_version_":1538287480707481601,"created_date":"2016-06-27T11:01:01.59Z"},{"tags":["PROD"],"id":"lp-whatsnewest","type":"response_value","display_type":"Redirect","search_terms":["whats newest"],"keys":["redirect"],"values":["http://stgewww.fingerhut.com/section/Our-Newest-Items/0002.uts"],"_version_":1538287480707481603,"created_date":"2016-06-27T11:01:01.59Z"},{"tags":["PROD"],"id":"lp-ournewestitems","type":"response_value","display_type":"Redirect","search_terms":["our newest items"],"keys":["redirect"],"values":["http://stgewww.fingerhut.com/section/Our-Newest-Items/0003.uts"],"_version_":1538287480707481604,"created_date":"2016-06-27T11:01:01.59Z"}]},"responseHeader":{"status":0,"QTime":0,"params":{"q":"*","facet.field":["display_type","tags","enabled"],"defType":"edismax","json.nl":"arrarr","lw.pipelineId":"bsb_products_rules-default","fl":"*","start":"0","isFusionQuery":"true","rows":"10","wt":"json","facet":"true"}},"facet_counts":{"facet_queries":{},"facet_fields":{"display_type":[["Boost",117],["Set Query Params",104],["Redirect",83],["Filter List",5],["Boost List",1]],"tags":[["PROD",304],["NEW",5],["TEST",1]],"enabled":[["true",6]]},"facet_dates":{},"facet_ranges":{},"facet_intervals":{},"facet_heatmaps":{}}}

**Comment by AlColeLW** [comment]
{"response":{"numFound":6,"start":0,"docs":[{"description":"Testing create a shop","display_type":"Filter List","tags":["NEW"],"updatedAt":[1467112938433],"search_terms":["xLucidworksx"],"field_name":"ProductID","created_date":"2016-06-28T11:11:47.744Z","createdAt":[1467111120565],"type":"filter_list","id":"LW CreateAShop 1","field_values":["NW445","NE368","NE368","ND900","NL089","NN943","NN805","NN859","F9158"],"enabled":true,"_version_":1538379416542904320},{"description":"Testing the category id.","display_type":"Filter List","tags":["NEW"],"updatedAt":[1467112938433],"filters":["CategoryID:645"],"field_name":"ProductID","created_date":"2016-06-28T11:13:35.035Z","createdAt":[1467112415023],"type":"filter_list","id":"LW CreateAShop 2","field_values":["NW445","NE368","NE368","ND900","NL089","NN943","NN805","NN859","F9158"],"enabled":true,"_version_":1538379416543952896},{"description":"Testing 1000 ids.","display_type":"Filter List","tags":["NEW"],"updatedAt":[1467114873681],"search_terms":["xAllProductsx"],"field_name":"ProductID","createdAt":[1467114863182],"type":"filter_list","id":"LW CreateAShop 3","field_values":["G9352","px244","PX244","PG108","G9091","PX290","RF665","QE518","RF666","QE517","PG095","qw825","GB371","QE515","QF312","PF596","PF394","RL123","PA189","RL127","RL062","RF672","RL060","PJ205","g8374","g8370","G9089","RL109","QE521","RC994","QF314","RL114","qs687","PS100","RL112","RL059","QD611","PS240","g8369","QN122","QC530","PX271","PT367","PX273","PB946","PR663","PX330","PY087","PY088","G9034","PF230","RF654","KB775","NZ486","PF604","PX289","GW575","PA210","RD011","RD004","PV730","QE714","RD009","RD006","QW577","PX257","PX259","PY686","PX254","PE617","PX352","G8998","PF263","PU919","PF350","QG333","QX415","PS096","PC926","GA916","PX361","RR179","PY614","PX263","G8369","PG141","PU938","G8915","G9181","PG139","PU935","PY004","RE389","NN231","GB359","PF287","PU350","PU356","PF289","PU354","qw794","PF319","RE379","PE597","qe757","PD745","GB366","RC027","PU349","PU348","QE757","NP156","NM322","PW352","QF337","RN285","RN280","RN277","RN278","GB360","RN282","GB380","PE473","RE380","RN287","RN284","RN283","RE390","RN279","RN281","PG108","G9091","PX290","RF665","QE518","RF666","QE517","PG095","qw825","GB371","QE515","QF312","PF596","PF394","RL123","PA189","RL127","RL062","RF672","RL060","PJ205","g8374","g8370","G9089","RL109","QE521","RC994","QF314","RL114","qs687","PS100","RL112","RL059","QD611","PS240","g8369","QN122","QC530","PX271","PT367","PX273","PB946","PR663","PX330","PY087","PY088","G9034","PF230","RF654","KB775","NZ486","PF604","PX289","GW575","PA210","RD011","RD004","PV730","QE714","RD009","RD006","QW577","PX257","PX259","PY686","PX254","PE617","PX352","G8998","PF263","PU919","PF350","QG333","QX415","PS096","PC926","GA916","PX361","RR179","PY614","PX263","G8369","PG141","PU938","G8915","G9181","PG139","PU935","PY004","RE389","NN231","GB359","PF287","PU350","PU356","PF289","PU354","qw794","PF319","RE379","PE597","qe757","PD745","GB366","RC027","PU349","PU348","QE757","NP156","NM322","PW352","QF337","RN285","RN280","RN277","RN278","GB360","RN282","GB380","QN492","QN495","QN498","QN498","QN495","TI465","TI466","TI467","QN442","TI458","QN498","QN492","TI460","QN498","QN498","QN574","QE838","QN574","QE838","QN495","QN570","QN494","QC905","QE838","QE838","TI450","QN430","QN430","QN430","QN430","QN430","QN430","QC940","QN347","QN347","QN347","QN347","QN347","QN347","QN347","QN347","QN347","QN347","TI388","QE909","QE909","QE909","QE946","QE947","QE946","QE946","QE946","QE946","QE946","NJ989","NJ989","NJ989","NJ989","NJ989","NJ989","NJ989","NJ989","QE946","QE947","QE947","QE947","QE946","QE946","QE907","QE916","QE916","QE916","NJ989","NJ989","NJ989","NJ989","NJ989","RR970","RR970","QE947","QE947","QE947","QE933","QE933","QE933","QE939","QE939","QE931","QE931","QE931","QE932","QE932","QE932","QE932","QE933","QE934","QE934","QE934","QE835","QE839","QE839","QE839","QE839","QE839","QE839","QN221","RR970","QE839","QE839","TI224","TI201","TI225","QE819","QE835","QE835","QE835","QE835","QE835","QE835","QE835","QE835","QE819","QE877","QE819","QE819","QE819","QE819","QE819","QE874","QE874","QE879","TG354","TG370","TG376","TG385","TG391","TG389","QC923","QC920","QL393","RY346","QL393","QL393","QL394","QC901","QL394","QL393","TG310","QC913","TG337","QL392","QL393","QL392","QL394","QL393","QL394","QL393","QL394","QL394","QL394","QL392","QL392","QL392","TG284","UK848","TG210","TG214","RP850","QL393","QL392","QL394","QC654","TG286","TG243","QC859","TG182","TG202","QC647","QC653","RY104","QL099","RY186","TG019","TG061","UK702","TP049","QC656","QC650","QC659","QC659","QC659","QC656","QC656","QC657","QC657","QC658","QC658","QC659","QC661","QC665","QC661","QC664","QC664","QC664","QC662","QC660","QC662","QC662","TG503","TG520","QC665","QC665","QL577","TP078","TP073","RY795","QU105","TG700","TG603","RY794","RY799","TG600","QU044","QU044","TP019","QL655","QU048","QU048","QU045","QU045","QU038","QU038","QU038","QU037","TP020","TP005","TG601","QL637","QL637","TG589","TG598","NQ623","NQ623","NQ623","QL523","TG559","TG522","TG585","TG583","QL989","TG586","TG486","QL566","TG447","QL453","QL453","QL455","QL455","QL455","QL454","QL452","QL453","QL454","TG446","TG429","TG989","TG489","QL451","SC476","TG838","SC469","SC470","SC473","SC439","SC437","PH552","PH557","TG990","TG991","TG992","SC938","TG993","TG997","SC468","QL987","QL991","SC373","QL968","QL939","QL937","QL939","QL937","QL937","QL937","QL937","QL937","QL937","QL937","QL937","QL937","QL937","TP344","TP281","QL937","QL939","QL937","TP336","QL937","QL939","QL939","TP282","TG839","SC207","SC859","SC859","SC859","SC859","SC859","SC859","SC859","SC280","SC824","SC289","SC859","SC859","SC859","SC859","SC859","TP279","TP885","TP885","TP885","SL215","SC872","TP885","SC928","SL126","SL126","SL126","SL126","SL126","TP885","TP885","SC857","SC857","SC857","SC857","SC857","SC858","SC857","SC857","SC857","SC857","TP885","TP885","TP885","TP885","TP885","SC865","SC865","SC849","SC825","TP885","SC858","SC858","SC858","TP885","SC858","SC865","SC865","SC865","SC865","SC865","SC865","SL127","SL127","SL127","SL127","SL514","SC779","SC778","SL188","SL723","SL494","SU215","SL742","SL739","SL780","SL715","SL717","SL708","SL726","SL731","SL728","SL515","SL516","SL523","SL524","SL521","SL564","SL509","PZ048","SL511","SL511","SL473","SL662","SL457","SL457","SL450","SL450","SL472","SL467","SL448","SL492","SL488","SL484","SL458","SL458","SL487","SL493","QD032","RH660","QD032","QD032","RH660","QD032","QD032","QD032","QD032","QD032","QD032","QD032","UL019","UL019","UL019","UL019","UL019","UL019","UL019","UL019","UL019","UL019","PZ613","F0786","F0786","F0786","F0786","F0786","F0786","UL019","UL019","UL019","UL019","SL948","RH359","SU376","SU373","SU808","SU808","SU477","QD222","SU290","RH359","SU258","QD436","QD465","QD363","QD362","QD415","QD418","QD496","QD496","QD496","QD496","QD496","QD496","QD414","QD416","QD421","QD394","RQ380","TH273","TH230","SU864","UL038","UL038","UL038","UL038","UL038","SU870","UL038","QD244","QD225","QD147","QD147","QD135","QD135","QD135","QD135","TH165","TH154","QD283","TH278","TH249","QM281","TH255","TH241","TH197","TH235","TH239","TH254","TH263","TH251","TH271","TH203","UU257","TH225","TH232","TH217","UL847","TH277","QD822","QD822","QD824","QD824","QD824","QD822","QD824","TH036","TH298","QD807","QM208","QD824","QD824","QD824","QD824","QD881","TH136","TH139","TH133","TH134","TH146","TH115","QD881","QD881","QD881","QD881","QD881","QD881","QD881","QD881","QD881","TH103","TH107","TH105","TH170","TH178","TH179","TH169","TH160","TH166","TH168","TH106","TH111","TH110","TH180","TH083","TH082","TH184","TH176","TH191","TH190","TH192","TH006","TH090","TH195","TH196","TH022","TH028","TH198","TH093","TH092","TH099","TH042","TH049","TH040","TH047","TH037","TH059","TH060","TH068","TH072","TH070","NR039","NR039","NR039","NR039","NR039","QD632","QD630","QD630","UL573","NR039","NR039","TJ914","TJ914","TJ914","TJ914","TJ914","UL581","SF347","SF359","SF332","SF693","PT518","PT518","PT518","PT518","PT518","PT518","PT518","PT518","SF315","SF308","TJ918","TJ918","TJ916","TJ916","TJ909","TJ909","RB308","PK999","TJ916","TJ917","TJ917","TJ917","TJ918","TJ916","RB319","SF311","TJ918","TJ917","QX891","QX891","QX708","SF875","SF878","QX840","PT376","RB948","SX197","SX155","SX156","QX707","P1271","SX074","SX075","SX090","F3062","RB608","QG125","QG125","QG125","QG125","QG541","QG541","QG541","QG066","QG066","QG066","QG066","QG541","QG541","QG066","QG066","QG066","QG124","QG124","QG124","QG124","QG075","SX639","QG066","QG088","QG012","SX637","SX636","SX630","SX634","SX529","SX599","SX911","SX632","SX565","SX556","SX594","SX623","QG020","RK518","RT255","SX427","SX427","NL276","NL276","NL276","NL276","TB459","RT221","SX346","TB548","NL276","NL276","NL276","RT467","SX902","QG374","TK284","QG300","QG372","QG375","SX883","RT223","TB880","QG369","QG374","QG201","QG201","QG201","TK251","TK160","QG763","QG763","QG772","QG772","TK107","QG189","QG189","TK120","QG191","TB633","QG886","QG887","QG886","TK275","TK285","TK282","TB690","QG887","TB978","TK384","QG848","QG848","QG848","TK269","TB690","QG869","QG866","QG887","QG887","TK253","TK743","TK256","QG866","QG866","TB860","TB860","TK227","TK248","TK226","TK205","TK203","TK264","TK263","TK211","TK214","TK201","TK258","TK213","TK200","TK259","TK261","TK190","TB896","TK171","TK172","TK169","TK178","TK181","TK187","TK165","TK164","TK163","TK162","TK149","TK159","TK155","TK197","TK194","TK198","TK189","TK161","TK188","TK220","TB783","TB783","TB783","TB783","TK074","TK084","TK083","TK108","TB766","TK110","TB766","TK114","TB766","TK118","TK121","TK125","TK082","TK145","TK136","TK134","TK131","TK777","TK769","TK784","TK527","TK783","TK778","TK779","TK751","TK752","PL130","PL130","PL130","TK704","TK709","PL130","PL130","PL130","SG178","TK551","TK546","TK710","TK724","TK725","TK736","TK726","SG191","TK787","TK459","TK416","SG549","TK426","TK741","TK503","TK667","TK665","TK500","TK647","TK648","TK666","TK657","TK698","TK664","TK620","TK529","TK530","TK508","TK525","TK509","TK524","TK520","TK507","TK523","QP416","QP416","TK415","TK412","TK482","TK486","TK474","TK483","TK422","TK478","QY472","QY455","TK989","TK457","TT425","QP835","QP828","QP824","QP804","QY226","TK899","SG210","TK898","TK934","QW135","QW107","SN064","QW639","SE512","SE512","SE512","SE512","SN004","SE512","SE512","SN309","SN309","SN309","SN309","SN309","SN309","SN309","SE493","QW417","SN309","SN367","SN377","SN309","SN609","SN611","SN309","SN309","SN309","SN347","SN611","QW901","SN318","SN363","SN363","SN378","SN378","SN363","SN360","SN349","SN331","SN325","SN341","SN835","SW428","SW413","SW413","SW419","SW419","SW413","SW413","RJ424","RJ422","RJ422","SW374","SW362","SW316","SN977","RJ422","RJ422","RJ422","RJ422","RJ305","RJ309","RJ422","RJ422","RJ422","SN925","SN769","SN772","SN771","UN114","SN799","SN793","SN789","SN822","SN822","SN822","SN777","SN777","SN750","SN763","SN754","SN823","SN823","SN743","SN631","SN626","SN624","SN631","SN631","SN631","SN632","SN620","SN615","SN634","UN107","TA182","UN105","UN108"],"enabled":true,"_version_":1538381445801705472,"created_date":"2016-06-28T11:54:33.697Z"},{"description":"Testing of manual ranking.","display_type":"Boost List","tags":["TEST"],"updatedAt":[1467117015063],"filters":["CategoryID:645"],"field_name":"ProductID","createdAt":[1467116940760],"type":"boost_list","id":"LW Manual Ranking 1","field_values":["NW445","NE368","NE368","ND900","NL089","NN943","NN805","NN859","F9158"],"enabled":true,"_version_":1538383691198234624,"created_date":"2016-06-28T12:30:15.074Z"},{"description":"Testing create a shop with dates.","display_type":"Filter List","tags":["NEW"],"updatedAt":[1467118352141],"search_terms":["xShopDatex"],"field_name":"ProductID","created_date":"2016-06-28T12:49:12.954Z","createdAt":[1467118152942],"type":"filter_list","effective_range":["[2016-06-26T00:00 TO 2016-07-01T00:00]"],"id":"LW Create-A-Shop 4","field_values":["NW445","NE368","NE368","ND900","NL089","NN943","NN805","NN859","F9158"],"enabled":true,"_version_":1538385093228232704},{"description":"Test tigger dates","display_type":"Filter List","tags":["NEW"],"updatedAt":[1467118352142],"field_name":"ProductID","created_date":"2016-06-28T12:51:04.308Z","createdAt":[1467118264296],"type":"filter_list","effective_range":["[2016-06-26T00:00 TO 2016-07-01T00:00]"],"id":"LW CreateAShop 4","field_values":["NW445","NE368","NE368","ND900","NL089","NN943","NN805","NN859","F9158"],"enabled":true,"_version_":1538385093235572736}]},"responseHeader":{"status":0,"QTime":0,"params":{"q":"LW_","facet.field":["display_type","tags","enabled"],"defType":"edismax","json.nl":"arrarr","lw.pipelineId":"bsb_products_rules-default","fl":"_","start":"0","isFusionQuery":"true","rows":"10","wt":"json","facet":"true"}},"facet_counts":{"facet_queries":{},"facet_fields":{"display_type":[["Filter List",5],["Boost List",1],["Boost",0],["Redirect",0],["Set Query Params",0]],"tags":[["NEW",5],["TEST",1],["PROD",0]],"enabled":[["true",6]]},"facet_dates":{},"facet_ranges":{},"facet_intervals":{},"facet_heatmaps":{}}}
