### ISSUE TITLE
 Ensure an update is performed and not an add

### ISSUE THREAD

**Issue by AlexKolonitsky** [AlexKolonitsky/lucidworks-view#72]
During an Edit Rule operation, if you change the name of the rule the operation results in the addition of a new rule (not an update) which creates a duplicate rule except for the name differences.  You must ensure an update is performed and not an add.

**Comment by AlColeLW** [comment]
I am still able to create duplicate rules by editing the rule name.

![duplicaterule](https://cloud.githubusercontent.com/assets/15756569/18887757/69bb9c72-84c3-11e6-8f01-73b9922da79b.png)

**Comment by AlexKolonitsky** [comment]
Issue reproduced when you first add new rule and edit it while it still be in first line.
