### ISSUE TITLE
Predefine list of tag names

### ISSUE THREAD

**Issue by AlexKolonitsky** [AlexKolonitsky/lucidworks-view#75]
Ability to define a predefine list of tag names in the "FUSION_CONFIG.js" file.  If no list is defined then the current behavior would continue.  Otherwise, the list of tags would be constrained to only those defined in the "FUSION_CONFIG.js' file.

**Comment by AlColeLW** [comment]
I see the configuration entry in FUSION_CONFIG.js, but the list is not enforced in the add rule form.
